# Generated by Django 3.2.5 on 2021-08-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='firtsNumber',
            new_name='firstNumber',
        ),
    ]
